CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" text NOT NULL,
        "Name" text NOT NULL,
        "Username" text NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Image" text NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE TABLE "Receipts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Steps" text[] NOT NULL,
        "MinCookDuration" integer NOT NULL,
        "MaxCookDuration" integer NOT NULL,
        CONSTRAINT "PK_Receipts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Receipts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE TABLE "Ingredient" (
        "Name" text NOT NULL,
        "Quantity" double precision NOT NULL,
        "Unit" text NOT NULL,
        "Optional" boolean NOT NULL,
        "ReceiptId" integer NULL,
        CONSTRAINT "PK_Ingredient" PRIMARY KEY ("Name"),
        CONSTRAINT "FK_Ingredient_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE TABLE "Subscriptions" (
        "UserId" integer NOT NULL,
        "ReceiptId" integer NOT NULL,
        CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("UserId", "ReceiptId"),
        CONSTRAINT "FK_Subscriptions_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE INDEX "IX_Ingredient_ReceiptId" ON "Ingredient" ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE INDEX "IX_Receipts_UserId" ON "Receipts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE INDEX "IX_Subscriptions_ReceiptId" ON "Subscriptions" ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823121950_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230823121950_Initial', '7.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    ALTER TABLE "Ingredient" DROP CONSTRAINT "FK_Ingredient_Receipts_ReceiptId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    ALTER TABLE "Ingredient" DROP CONSTRAINT "PK_Ingredient";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    DROP INDEX "IX_Ingredient_ReceiptId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    UPDATE "Ingredient" SET "ReceiptId" = 0 WHERE "ReceiptId" IS NULL;
    ALTER TABLE "Ingredient" ALTER COLUMN "ReceiptId" SET NOT NULL;
    ALTER TABLE "Ingredient" ALTER COLUMN "ReceiptId" SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    ALTER TABLE "Ingredient" ADD "Id" integer GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    ALTER TABLE "Ingredient" ADD CONSTRAINT "PK_Ingredient" PRIMARY KEY ("ReceiptId", "Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    ALTER TABLE "Ingredient" ADD CONSTRAINT "FK_Ingredient_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230823132010_Second') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230823132010_Second', '7.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    DROP TABLE "Subscriptions";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    ALTER TABLE "Receipts" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    ALTER TABLE "Receipts" ADD "Description" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    ALTER TABLE "Receipts" ADD "ImageLinks" text[] NOT NULL DEFAULT ARRAY[]::text[];
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    ALTER TABLE "Receipts" ADD "Title" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    ALTER TABLE "Receipts" ADD "VideoLink" text NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE TABLE "Ratings" (
        "UserId" integer NOT NULL,
        "ReceiptId" integer NOT NULL,
        "Value" integer NOT NULL,
        CONSTRAINT "PK_Ratings" PRIMARY KEY ("UserId", "ReceiptId"),
        CONSTRAINT "FK_Ratings_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Ratings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE TABLE "Reviews" (
        "UserId" integer NOT NULL,
        "ReceiptId" integer NOT NULL,
        "ReviewText" text NOT NULL,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("UserId", "ReceiptId"),
        CONSTRAINT "FK_Reviews_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE TABLE "SubscriptionsReceipt" (
        "UserId" integer NOT NULL,
        "ReceiptId" integer NOT NULL,
        "SubscriptionStart" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SubscriptionsReceipt" PRIMARY KEY ("UserId", "ReceiptId"),
        CONSTRAINT "FK_SubscriptionsReceipt_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SubscriptionsReceipt_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE TABLE "SubscriptionsUser" (
        "UserId" integer NOT NULL,
        "UserSubscribedToId" integer NOT NULL,
        "SubscriptionStart" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SubscriptionsUser" PRIMARY KEY ("UserId", "UserSubscribedToId"),
        CONSTRAINT "FK_SubscriptionsUser_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SubscriptionsUser_Users_UserSubscribedToId" FOREIGN KEY ("UserSubscribedToId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE INDEX "IX_Receipts_CreatedAt" ON "Receipts" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE INDEX "IX_Ratings_ReceiptId" ON "Ratings" ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE INDEX "IX_Reviews_ReceiptId" ON "Reviews" ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE INDEX "IX_SubscriptionsReceipt_ReceiptId" ON "SubscriptionsReceipt" ("ReceiptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    CREATE INDEX "IX_SubscriptionsUser_UserSubscribedToId" ON "SubscriptionsUser" ("UserSubscribedToId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230904120333_ReceiptModified') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230904120333_ReceiptModified', '7.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230908133418_DateFormatChanged') THEN
    ALTER TABLE "Ingredient" ALTER COLUMN "Unit" TYPE character varying(8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230908133418_DateFormatChanged') THEN
    ALTER TABLE "Ingredient" ALTER COLUMN "Name" TYPE character varying(64);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230908133418_DateFormatChanged') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230908133418_DateFormatChanged', '7.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230913103442_DateAddedToReview') THEN
    ALTER TABLE "Reviews" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230913103442_DateAddedToReview') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230913103442_DateAddedToReview', '7.0.9');
    END IF;
END $EF$;
COMMIT;

