// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReceiptSharing.Api.Models;

#nullable disable

namespace _.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230908133418_DateFormatChanged")]
    partial class DateFormatChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReceiptSharing.Api.Models.Rating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ReceiptId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("ImageLinks")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("MaxCookDuration")
                        .HasColumnType("integer");

                    b.Property<int>("MinCookDuration")
                        .HasColumnType("integer");

                    b.Property<string[]>("Steps")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.Review", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "ReceiptId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.SubscriptionReceipt", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubscriptionStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ReceiptId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("SubscriptionsReceipt");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.SubscriptionUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserSubscribedToId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubscriptionStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "UserSubscribedToId");

                    b.HasIndex("UserSubscribedToId");

                    b.ToTable("SubscriptionsUser");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.Rating", b =>
                {
                    b.HasOne("ReceiptSharing.Api.Models.Receipt", "Receipt")
                        .WithMany("Ratings")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceiptSharing.Api.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.Receipt", b =>
                {
                    b.HasOne("ReceiptSharing.Api.Models.User", "User")
                        .WithMany("Receipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("ReceiptSharing.Api.Models.Ingredient", "Ingredients", b1 =>
                        {
                            b1.Property<int>("ReceiptId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("Optional")
                                .HasColumnType("boolean");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)");

                            b1.HasKey("ReceiptId", "Id");

                            b1.ToTable("Ingredient");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId");
                        });

                    b.Navigation("Ingredients");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.Review", b =>
                {
                    b.HasOne("ReceiptSharing.Api.Models.Receipt", "Receipt")
                        .WithMany("Reviews")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceiptSharing.Api.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.SubscriptionReceipt", b =>
                {
                    b.HasOne("ReceiptSharing.Api.Models.Receipt", "Receipt")
                        .WithMany("SubscriptionsReceipt")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceiptSharing.Api.Models.User", "User")
                        .WithMany("SubscriptionsReceipt")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.SubscriptionUser", b =>
                {
                    b.HasOne("ReceiptSharing.Api.Models.User", "User")
                        .WithMany("Subscribers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceiptSharing.Api.Models.User", "UserSubscribedTo")
                        .WithMany("SubscribedTo")
                        .HasForeignKey("UserSubscribedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserSubscribedTo");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.Receipt", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("SubscriptionsReceipt");
                });

            modelBuilder.Entity("ReceiptSharing.Api.Models.User", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Receipts");

                    b.Navigation("Reviews");

                    b.Navigation("SubscribedTo");

                    b.Navigation("Subscribers");

                    b.Navigation("SubscriptionsReceipt");
                });
#pragma warning restore 612, 618
        }
    }
}
